id: PB1F01C72
initial_creation_type: input
source_metadata:
  title: Fifth Dzogchen Rinpoche
  language: bo
  description: 'Texts by and about the Fifth Dzogchen Rinpoche, Thupten Chökyi Dorje
    (rdzogs chen thub bstan chos kyi rdo rje, 1872–1935):'
  volume:
    66ac8de083b54fe28cfc5660a9ca3a19:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    4845c8ee1cfb443a828dd4d17eaa53ae:
      title: Brief Protectors Practice
      parent: Dharma Protectors
    6c3e74a097bc4166afa1189ffaf17dda:
      title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black
        Hayagrīva with an Iron Sword
      parent: Hayagrīva
    e55c27ecf9b642f0885fe671d4acfcfd:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T23:15:06.345481'
last_modified_at: '2022-02-28T23:15:06.345484'
statistics:
  total_words: 356
  total_non_words: 26
quality:
  non_words_ratio: 0.07
